#!/bin/bash
# Rebase helper: re-apply NewsReader decoy patches after upstream Telegram merge
# Usage: bash rebase_after_merge.sh

set -e

echo "=== Re-applying NewsReader Decoy patches ==="
echo ""
echo "After merging upstream, re-apply these 4 manual changes:"
echo ""
echo "1. gradle.properties — APP_PACKAGE"
echo "   Change: APP_PACKAGE=org.telegram.messenger"
echo "   To:     APP_PACKAGE=org.newsrss.reader"
echo ""
echo "2. TMessagesProj_App/build.gradle — dependencies"
echo "   Ensure these are added:"
echo "     implementation 'androidx.room:room-runtime:2.6.1'"
echo "     implementation 'androidx.room:room-ktx:2.6.1'"
echo "     kapt 'androidx.room:room-compiler:2.6.1'"
echo "     implementation 'androidx.work:work-runtime-ktx:2.9.0'"
echo "     implementation 'com.github.bumptech.glide:glide:4.16.0'"
echo "     implementation 'com.google.android.material:material:1.11.0'"
echo "     implementation 'androidx.appcompat:appcompat:1.6.1'"
echo "     implementation 'androidx.recyclerview:recyclerview:1.3.2'"
echo "     implementation 'androidx.constraintlayout:constraintlayout:2.1.4'"
echo "     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'"
echo "   And: apply plugin: 'kotlin-kapt'"
echo ""
echo "3. TMessagesProj/src/main/AndroidManifest.xml"
echo "   - Add DecoyActivity with MAIN/LAUNCHER intent-filter"
echo "   - Disable DefaultIcon (android:enabled="false")"
echo ""
echo "4. TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java"
echo "   - Add import org.telegram.decoy.DecoyReturnHelper;"
echo "   - Add setupNewsReaderReturnGesture() call in onCreate"
echo "   - Add the setupNewsReaderReturnGesture method"
echo ""
echo "All new files in org/telegram/decoy/ and res/ merge automatically."
echo "Total manual effort: ~5 minutes."
